spencerterry1/menyoo

- Gemfile
- Gemfile.lock
- app/controllers/users_controller.rb
- app/models/user.rb
- app/uploaders/photo_uploader.rb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20190827193052_add_columns_to_users.rb
- db/migrate/20190827193601_add_photo_to_users.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/users_controller_test.rb
- Created User model
- Created User controller (skeleton)
- Created User view (skeleton)
- Added Cloudinary 
- Created User seeds
> added user model and user seeds

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/models/restaurant.rb
- app/models/user.rb
- app/views/bookings/show.html.erb
- config/routes.rb
- db/migrate/20190829191408_create_bookings.rb
- db/migrate/20190829191648_add_date_to_booking.rb
- db/migrate/20190829192502_change_booking_date_data_type.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/bookings_controller_test.rb
- test/models/booking_test.rb
set up booking model, routes, controller and views (with test seeds)
> set up booking model, routes, controller and views

- .gitignore
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/config/_variables.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/restaurants/index.html.erb
- app/views/restaurants/show.html.erb
- app/views/shared/_navbar_ios.html.erb
- app/views/shared/_tabbar_ios.html.erb
- config/routes.rb
- db/schema.rb
- Added Restaurant views for testing Restaurant and Dishes
- Started Front End of Navbar
> Restaurant views

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_variables.scss
- app/assets/stylesheets/pages/_home.scss
- app/models/dish.rb
- app/views/restaurants/index.html.erb
- app/views/restaurants/show.html.erb
- app/views/shared/_navbar_ios.html.erb
- config/initializers/money.rb
- db/migrate/20190831141058_remove_price_from_dishes.rb
- db/migrate/20190831141332_add_price_to_dishes.rb
- db/schema.rb
- db/seeds.rb
> More front

- Gemfile
- Gemfile.lock
- app/controllers/bookings_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/models/user.rb
- app/views/bookings/new.html.erb
- config/routes.rb
- db/schema.rb
- db/seeds.rb
- package.json
- yarn.lock
- Created booking model
- Set up routes
- Added controller
- Created basic views to (1) load booking form and (2) create a new booking (and be redirected to the new booking that is just created)
> added booking model, route, controller and (basic) view

- app/assets/stylesheets/components/_navbar.scss
- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/restaurants_controller.rb
- app/controllers/users_controller.rb
- app/models/booking.rb
- app/views/bookings/new.html.erb
- app/views/layouts/application.html.erb
- app/views/restaurants/show.html.erb
- app/views/shared/_tabbar_ios.html.erb
- app/views/users/show.html.erb
- db/migrate/20190907102511_add_open_to_bookings.rb
- db/schema.rb
- db/seeds.rb
See list of commits for details
> Attendee index

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/controllers/application_controller.rb
- app/controllers/attendees_controller.rb
- app/controllers/users_controller.rb
- app/views/attendees/index.html.erb
- app/views/bookings/show.html.erb
- app/views/users/show.html.erb
- config/routes.rb
> Invitations

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/restaurants_controller.rb
- app/models/dish.rb
- app/models/restaurant.rb
- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- app/views/restaurants/index.html.erb
- app/views/restaurants/show.html.erb
- app/views/shared/_tabbar_ios.html.erb
- config/routes.rb
- db/schema.rb
- db/seeds.rb
See list of commits for details
> Attendees and bookings

- db/seeds.rb
You can now see the number of reviews next to the stars in the index page, plus all the list of reviews in the show page..I made proper reviews for the restaurant Polpo, which is the one we picked last time, for the rest of restaurants I gave only a good or bad review. However, I think we should add a date and title to the review and maybe display them in date order, with newest on top.
> Seeds bookings and reviews

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_rating.scss
- app/assets/stylesheets/pages/_checkedin.scss
- app/views/attendees/index.html.erb
- app/views/restaurants/show.html.erb
- app/views/shared/_checkedin.html.erb
- app/views/shared/_navbar_ios.html.erb
- app/views/users/show.html.erb
- db/seeds.rb
- Amended formatting on Restaurant & Dish cards (changed formatting to $menyoo-blue)
- Amended seeds where Restaurant name and Dish description are too long (all are 2 lines only now)
- On user profile, vertically centred titles for cards ('Bookings', 'Log Out' etc)
> Restaurant cards formatting

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_checkedin.scss
- app/views/attendees/index.html.erb
- app/views/restaurants/show.html.erb
- app/views/shared/_checkedin.html.erb
- app/views/shared/_navbar_ios.html.erb
- Changed colour of checkin button back to $menyoo-blue (looks nicer!)
- Fixed formatting of the modal pop up (QR code screen)
> Checkin button

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/views/attendees/index.html.erb
- app/views/restaurants/show.html.erb
- When searching for attendees, aligned the search bar and the search button
- On the attendee that is returned after a successful search, aligned the photo, name and invite button
- When invite sent, added blue border to invitees who have accepted the invitation
> fixed formatting for attendee invite page

- app/assets/stylesheets/components/_card.scss
- app/controllers/reviews_controller.rb
- db/seeds.rb
- Amended order total error that was preventing the order_total variable being passed to stripe because was in wrong format
- Removed seed for the 'Chippy' as was causing errors with layout ('black space issue')
> amended order total

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_modals.scss
- app/controllers/restaurants_controller.rb
- app/javascript/packs/application.js
- app/views/restaurants/show.html.erb
- app/views/shared/_checkedin.html.erb
- app/views/shared/_newbookingmodal.html.erb
See list of commits for details
> Table order ui

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/views/bookings/summary.html.erb
Amended order cards on the Summary page
> improved card layout for orders on summary page

- app/assets/stylesheets/components/_button.scss
- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
- app/views/restaurants/index.html.erb
- app/views/restaurants/show.html.erb
- config/initializers/default_meta.rb
- config/meta.yml
Followed Le Wagon's instructions on meta data set up
> Meta data setup

- app/assets/stylesheets/components/_button.scss
- app/javascript/packs/application.js
- app/views/restaurants/index.html.erb
- app/views/restaurants/show.html.erb
Applies to 2 search bars
- Restaurant Index search bar (to search restaurants on landing page)
- Restaurant Show search bar (to search dishes)
> added buttons in search bars to erase search when user types in

- app/assets/stylesheets/components/Find Results
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_map.scss
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/views/restaurants/index.html.erb
- db/migrate/20190918064950_add_price_cents_to_orders.rb
added iteration of restaurant names found in search under map
> changed map view

- app/javascript/packs/application.js
Issue was that the 'initializer' method in the javascript folder (application.js file) was commented out
> fixed issue with maps not showing

- app/views/bookings/summary.html.erb
- app/views/restaurants/show.html.erb
Stars and the number of stars were previously being displayed on separate lines - now fixed
> amended star rating view

- app/assets/stylesheets/components/_button.scss
- app/views/attendees/index.html.erb
- db/schema.rb
Wrong class was applied so the 'invite attendees' button on the attendees index page was not showing when the user tried to invite after searching
> fixed CSS error on invite attendees button

- app/assets/stylesheets/pages/_home.scss
- app/views/reviews/new.html.erb
> improved formatting of new review form

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_modals.scss
- app/controllers/bookings_controller.rb
- app/javascript/packs/application.js
- app/views/bookings/summary.html.erb
- app/views/shared/_newreviewmodal.html.erb
- db/seeds.rb
See list of commits for details
> Ux improvements

- app/assets/stylesheets/components/_button.scss
- app/views/bookings/summary.html.erb
On the order summary page for 'orders sent to kitchen'
> added status button to highlight when other attendees haven't yet paid

- app/assets/stylesheets/components/_card.scss
- app/views/bookings/summary.html.erb
Amended order status buttons so that current user can see status of other attendees orders (previously, current user could only see if another user had paid, and not whether their status was 'unpaid')
> amend-order-summary-status-buttons

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/config/_fonts.scss
- app/controllers/bookings_controller.rb
- app/views/bookings/show.html.erb
- config/routes.rb
Added:
- Added button to Booking Show page, restaurant image (user only sees when they are lead booker and NO orders have been sent to kitchen yet)
- Bookings Delete route added
- Destroy method added in bookings controller
- 'Close-button' CSS added
> added ability to delete bookings before paying

- app/assets/stylesheets/components/_avatar.scss
- app/views/bookings/show.html.erb
- Updated the `link_to` for the Closing Button so that it wraps the button itself (and makes the whole button clickable)
- Updated the background of the button to be transparent dark grey (so that the white font is easier to read when the background picture is light)
> Closing button

- app/assets/stylesheets/components/_button.scss
- app/views/restaurants/show.html.erb
To make it clearer for the attendee to understand that they haven't ordered/sent orders to kitchen
> When an attendee is not checked in, changed 'order' to 'pre-order' on restaurant show

- app/views/bookings/show.html.erb
Edited text for checkin banner (before User checks in)
> Checkin banner edit

- Gemfile
- Gemfile.lock
- app/assets/active_admin:base.scss
- app/assets/javascripts/active_admin.js
- app/assets/javascripts/application.js
- app/assets/stylesheets/active_admin.scss
- app/javascript/packs/application.js
- app/views/admin/dashboard/_index.html.erb
- config/initializers/active_admin.rb
Built out cards on admin dash with javascript to expand/minimise individual orders. Next step is to add AJAX to auto refresh the feed every 10 seconds.
> improved admin dashboard by adding ability to expand/contract orders

- app/admin/dashboard.rb
- app/assets/stylesheets/active_admin.scss
Added Menyoo font and colours to log in screens
> added menyoo stles to login page

- app/admin/admin_users.rb
- app/admin/booking.rb
- app/admin/dashboard.rb
- app/views/admin/bookings/refresh_orders.html.erb
- app/views/admin/bookings/refresh_orders.js.erb
- app/views/admin/dashboard/_index.html.erb
- app/views/admin/dashboard/_refresh_orders.html.erb
- app/views/shared/_ad_dashboard.html.erb
- app/views/shared/_admin_dashboard.html.erb
- config/initializers/active_admin.rb
Ajax request couldn't find file - now amended so properly routed
> Added ajax edit

- app/admin/booking.rb
- app/admin/dashboard.rb
- app/assets/javascripts/active_admin.js
- app/controllers/bookings_controller.rb
- app/controllers/orders_controller.rb
- app/views/admin/bookings/refresh_orders.js.erb
- app/views/admin/dashboard/_index.html.erb
- app/views/shared/_ad_dashboard.html.erb
Added mutation observer to detect when new orders are placed to notify user on dashboard
> added mutation observer - not yet working properly

- app/admin/booking.rb
- app/admin/dashboard.rb
- app/assets/javascripts/active_admin.js
- app/assets/stylesheets/active_admin.scss
- app/views/shared/_ad_dashboard.html.erb
Created a way of formatting new orders with a border around the order cards
> added fade in formatting to new orders

- app/admin/dashboard.rb
- app/assets/javascripts/active_admin.js
- app/assets/stylesheets/active_admin.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/controllers/bookings_controller.rb
- app/views/admin/dashboard/_index.html.erb
- app/views/admin/dashboard/refresh_orders.js.erb
- app/views/shared/_ad_dashboard.html.erb
- db/migrate/20200705155554_add_check_in_time_to_booking.rb
- db/migrate/20200708195047_add_payment_time_to_booking.rb
- db/migrate/20200709065915_add_bill_payment_to_booking.rb
- db/schema.rb
Tweaked dashboard to have 3 phases: (1) checkedin (2) ordered (3) closed
> Amend dashboard

- app/admin/dashboard.rb
- app/assets/javascripts/active_admin.js
- app/assets/stylesheets/active_admin.scss
- app/models/booking.rb
- app/views/shared/_ad_dashboard.html.erb
- db/migrate/20200716102144_add_service_status_to_booking.rb
- db/schema.rb
For orders that have been placed with kitchen, added option for Admin user / waiters to say that orders have been served to tables
> added logic to update orders when served by waiters
